export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const NEWS_DETAILS_REQUEST = 'NEWS_DETAILS_REQUEST';
export const NEWS_DETAILS_SUCCESS = 'NEWS_DETAILS_SUCCESS';
export const NEWS_DETAILS_FAIL = 'NEWS_DETAILS_FAIL';

export const NEWS_BY_CATEGORY_REQUEST = 'NEWS_BY_CATEGORY_REQUEST';
export const NEWS_BY_CATEGORY_SUCCESS = 'NEWS_BY_CATEGORY_SUCCESS';
export const NEWS_BY_CATEGORY_FAIL = 'NEWS_BY_CATEGORY_FAIL';

export const NEWS_BY_SOURCE_REQUEST = 'NEWS_BY_SOURCE_REQUEST';
export const NEWS_BY_SOURCE_SUCCESS = 'NEWS_BY_SOURCE_SUCCESS';
export const NEWS_BY_SOURCE_FAIL = 'NEWS_BY_SOURCE_FAIL';

export const NEWS_BY_BIAS_REQUEST = 'NEWS_BY_BIAS_REQUEST';
export const NEWS_BY_BIAS_SUCCESS = 'NEWS_BY_BIAS_SUCCESS';
export const NEWS_BY_BIAS_FAIL = 'NEWS_BY_BIAS_FAIL';

export const NEWS_SEARCH_REQUEST = 'NEWS_SEARCH_REQUEST';
export const NEWS_SEARCH_SUCCESS = 'NEWS_SEARCH_SUCCESS';
export const NEWS_SEARCH_FAIL = 'NEWS_SEARCH_FAIL';
export const NEWS_SEARCH_RESET = 'NEWS_SEARCH_RESET';
