export const SOURCE_LIST_REQUEST = 'SOURCE_LIST_REQUEST';
export const SOURCE_LIST_SUCCESS = 'SOURCE_LIST_SUCCESS';
export const SOURCE_LIST_FAIL = 'SOURCE_LIST_FAIL';

export const SOURCE_DETAILS_REQUEST = 'SOURCE_DETAILS_REQUEST';
export const SOURCE_DETAILS_SUCCESS = 'SOURCE_DETAILS_SUCCESS';
export const SOURCE_DETAILS_FAIL = 'SOURCE_DETAILS_FAIL';

export const SOURCE_BY_BIAS_REQUEST = 'SOURCE_BY_BIAS_REQUEST';
export const SOURCE_BY_BIAS_SUCCESS = 'SOURCE_BY_BIAS_SUCCESS';
export const SOURCE_BY_BIAS_FAIL = 'SOURCE_BY_BIAS_FAIL';
